POST http://localhost:3003/dog-walker/register
Content-Type: application/json

{
    "status": "CARRIED",
    "date": "2022/03/24",
    "time": "ONE_HOUR",
    "pets": 1,
    "price": 35,
    "latitude": 165741,
    "longitude": 1249,
    "start_time": 60,
    "end_time": 120
}